export const profileList = [

    {
        name: 'Shravya Shetty',
        githubUsername: 'Shravyarshetty',
        instagramUsername: 'shravya.r.shetty',
        twitterUsername: '',
        linkedinURL: 'linkedin.com/',
    },

    {
        name: 'N Rahul Rao ',
        githubUsername: 'RahulRao23',
        instagramUsername: '_.rahulrao._',
        twitterUsername: ' ',
        linkedinURL: ' ',

    },
    {
        name: 'Sharan sk',
        githubUsername: 'sharansk792000',
        instagramUsername: 'sharanskindalkar',
        twitterUsername: 'ShaKindalkar',
        linkedinURL: 'https://www.linkedin.com/in/sharan-sk-89260919b',
    },
    {
        name: 'Avni Shyam',
        githubUsername: 'avnishyam',
        instagramUsername: 'avni.shyam',
        twitterUsername: '@AvniShyam_2000',
        linkedinURL: 'https://www.linkedin.com/in/avni-shyam/',
    },
    {
        name: 'Vishnu N V',
        githubUsername: 'carbonxx',
        instagramUsername: 'ig_carbonx',
        twitterUsername: 'vishnu_nvx',
        linkedinURL: '',
    },
    {
        name: 'Prajwal Benedcict A',
        githubUsername: 'BENEDICT9845',
        instagramUsername: 'benedictprajwal',
        twitterUsername: 'BENEDICT9845',
        linkedinURL: 'https://www.linkedin.com/in/prajwal-benedict-a-048511186/',
    },
    {
        name: 'Nirmal GM',
        githubUsername: 'redfedted',
        instagramUsername: 'nirmal_g_m',
        twitterUsername: 'NirmalgMathew ',
        linkedinURL: 'https://www.linkedin.com/in/nirmal-george-mathew-170b62177/ ',
    },

    {
        name: 'Gowtham P B',
        githubUsername: 'GowthamPB',
        instagramUsername: 'gowtham_pb',
        twitterUsername: 'Gowtham_PB',
        linkedinURL: 'https://www.linkedin.com/in/gowtham-pb-325677191',
    },
    {
        name: 'Deeksha Shetty',
        githubUsername: 'Dharmaksha',
        instagramUsername: '',
        twitterUsername: '',
        linkedinURL: 'https://www.linkedin.com/mwlite/in/',
    },
    {
        name: 'Basavarajeshwari Ambi',
        githubUsername: 'Basavarajeshwari-Ambi',
        instagramUsername: 'sony18_99',
        twitterUsername: 'Basavarajeshw20',
        linkedinURL: 'https://www.linkedin.com/in/basavarajeshwari-ambi-1b223016a/',
    },
    {
        name: 'K Anusha Rao',
        githubUsername: 'K-ANUSHA-RAO',
        instagramUsername: 'anu_sha_45',
        twitterUsername: '',
        linkedinURL: 'https://www.linkedin.com/in/k-anusha-rao-92074417a/',
    },
    {
        name: 'Sumanth Kumar S',
        githubUsername: 'SumanthKumarS',
        instagramUsername: 'sumanthshettigar20k',
        twitterUsername: '',
        linkedinURL: 'www.linkedin.com/in/sumanth-kumar-s-57248320a',
    },
    {
        name: 'Nithin Mahendran',
        githubUsername: 'nithinmahendran',
        instagramUsername: 'nithinmahendran',
        twitterUsername: 'nithinmahendran',
        linkedinURL: 'linkedin.com/nithinmahendran',
    },
    {
        name: 'Akhilesh M',
        githubUsername: 'akhilesh27',
        instagramUsername: 'Akhilesh Naik',
        twitterUsername: '',
        linkedinURL: 'https://www.linkedin.com/in/akhilesh-naik-024475219/',
    },
    {
        name: 'Satyam singh',
        githubUsername: 'satyammmmmm',
        instagramUsername: 'satyammmmmm_',
        twitterUsername: '@satyam_singh12',
        linkedinURL: 'linkedin.com/in/satyam-singh-483673207 ',
    },
    {
        name: 'Haneena',
        githubUsername: 'hanx007',
        instagramUsername: 'haneena007',
        twitterUsername: 'Haneenaaaa',
        linkedinURL: 'https://www.linkedin.com/in/haneena-atheeq-007/',
    },

    {
       name:  'Niveditha T',
       githubUsername: 'nivedt',
       instagramUsername: '',
       twitterUsername: '@nzilch9',
       linkedinURL: '-',
    },
    {
       name:  'Manoj Naik',
       githubUsername: 'Manojnaik19',
       instagramUsername: '_manoj.naik_',
       twitterUsername: '',
       linkedinURL: 'https://www.linkedin.com/in/manoj-naik-35a718202/',
    },
    {
        name: 'Rachitha Rai',
        githubUsername: 'RachithaRai',
        instagramUsername: 'rachitha_rai_',
        twitterUsername: '',
        linkedinURL: 'https://www.linkedin.com/in/rachitha-rai-70040317b/',
    },
    {
        name: 'Fawaz Abid',
        githubUsername: 'fauwara',
        instagramUsername: 'fauwara',
        twitterUsername: 'fazxza',
        linkedinURL: '',
    },
    {
        name: 'Monish Shetty',
        githubUsername: 'alpha-oss',
        instagramUsername: 'shetty_monish_077',
        twitterUsername: 'MonishShetty07',
        linkedinURL: 'https://www.linkedin.com/in/monish-shetty-357392191',
    },

]
