export const profileList = [
    {
        name: 'Nirmal Mathew',
        githubUsername:'swaaz',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'RahulRao23',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'rachitharai',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'swaaz',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'swaaz',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'RahulRao23',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'rachitharai',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'swaaz',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'swaaz',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'RahulRao23',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'rachitharai',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'swaaz',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'swaaz',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'RahulRao23',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'rachitharai',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
    {
        name: 'Nirmal Mathew',
        githubUsername:'swaaz',
        instagramUsername:'_swaaz_',
        twitterUsername:'Swaaz07',
        linkedinURL:'linkedin.com',
    },
   
]

